task:
  name: FrankaCabinet
  physics_engine: ${..physics_engine}
  rl_device: ${..rl_device}
  env:
    numEnvs: ${resolve_default:4096,${...num_envs}}
    envSpacing: 1.5
    episodeLength: 1000
    enableDebugVis: false
    clipObservations: 5.0
    clipActions: 1.0
    startPositionNoise: 0.0
    startRotationNoise: 0.0
    numProps: 16
    aggregateMode: 3
    actionScale: 7.5
    dofVelocityScale: 0.1
    distRewardScale: 2.0
    rotRewardScale: 0.5
    aroundHandleRewardScale: 0.25
    openRewardScale: 7.5
    fingerDistRewardScale: 5.0
    actionPenaltyScale: 0.01
    asset:
      assetRoot: ../../assets
      assetFileNameFranka: urdf/franka_description/robots/franka_panda.urdf
      assetFileNameCabinet: urdf/sektion_cabinet_model/urdf/sektion_cabinet_2.urdf
    enableCameraSensors: false
  sim:
    dt: 0.0166
    substeps: 1
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 12
      num_velocity_iterations: 1
      contact_offset: 0.005
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 1000.0
      default_buffer_size_multiplier: 5.0
      max_gpu_contact_pairs: 1048576
      num_subscenes: ${....num_subscenes}
      contact_collection: 0
  task:
    randomize: false
train:
  params:
    seed: ${...seed}
    algo:
      name: sac
    model:
      name: soft_actor_critic
    network:
      name: soft_actor_critic
      separate: true
      space:
        continuous:
          fixed_sigma: false
      mlp:
        units:
        - 256
        - 128
        - 64
        activation: relu
        initializer:
          name: default
      log_std_bounds:
      - -5
      - 2
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:FrankaCabinetSAC_0613,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      multi_gpu: false
      normalize_input: true
      reward_shaper:
        scale_value: 1.0
      device: ${....rl_device}
      max_epochs: 10000
      num_steps_per_episode: 500
      save_best_after: 100
      save_frequency: 10000
      gamma: 0.99
      init_alpha: 1
      actor_lr: 0.0005
      critic_lr: 0.0005
      critic_tau: 0.005
      alpha_lr: 0.005
      batch_size: 1024
      learnable_temperature: true
      num_seed_steps: 5
      replay_buffer_size: 1000000
      mixed_precision: true
      normalize_value: true
      value_bootstrap: true
      num_actors: ${....task.env.numEnvs}
task_name: ${task.name}
experiment: ''
num_envs: 1024
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: false
checkpoint: ''
multi_gpu: false
headless: true
dataset: ''
save_hdf5_when_play: false
save_hdf5_folder: test_save/hdf5
